# Generated by Django 3.2 on 2022-10-02 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0003_alter_trainers_trainer_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trainers',
            options={'verbose_name': 'Trainer'},
        ),
        migrations.AddField(
            model_name='trainers',
            name='trainer_category',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterModelTable(
            name='trainers',
            table='Trainers',
        ),
    ]
