# Generated by Django 3.2 on 2022-10-02 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0004_auto_20221002_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainers',
            name='trainer_category',
            field=models.CharField(max_length=20),
        ),
    ]
