# Generated by Django 3.2 on 2022-10-03 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0006_alter_trainers_trainer_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainers',
            name='slug',
            field=models.SlugField(max_length=200, null=True, unique=True),
        ),
    ]
