# Generated by Django 3.2 on 2022-12-05 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0007_trainers_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainers',
            name='trainer_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
