# Generated by Django 3.2 on 2022-10-06 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trainers', '0007_trainers_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport', models.CharField(max_length=100)),
                ('sport_category', models.CharField(max_length=100)),
                ('sport_cost', models.DecimalField(decimal_places=2, max_digits=6)),
                ('sport_location', models.CharField(max_length=100)),
                ('sport_image', models.ImageField(default='placeholder', upload_to='')),
                ('trainer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainers.trainers')),
            ],
            options={
                'verbose_name_plural': 'Sports',
            },
        ),
    ]
