# Generated by Django 3.2 on 2022-10-06 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sports',
            old_name='sport',
            new_name='sport_type',
        ),
    ]
