# Generated by Django 3.2 on 2022-12-05 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0003_sports_sport_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sports',
            name='sport_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
